import {
  createEmptyGraphSummary,
  type MaterialDependency,
  type MaterialEntryType,
  type MaterialGraphSummary,
  type MaterialParameterValue
} from '../types/material'

export interface AssetLinkRecord {
  assetKey?: string
  assetName?: string
  softPath?: string
  className?: string
  classNameCn?: string
  imgLocalPath?: string
  customPoster?: string
}

export function createMaterialEntryId(entryType: MaterialEntryType, key: string): string {
  let hash = 0
  const seed = `${entryType}:${key}`

  for (let i = 0; i < seed.length; i++) {
    hash = (hash * 31 + seed.charCodeAt(i)) >>> 0
  }

  return `material-${entryType}-${hash.toString(16)}`
}

function extractGamePaths(value: unknown): string[] {
  const rawValue =
    typeof value === 'string'
      ? value
      : value && typeof value === 'object'
        ? JSON.stringify(value)
        : ''

  if (!rawValue.includes('/Game/')) return []

  return (rawValue.match(/\/Game\/[A-Za-z0-9_./]+/g) || []).map(normalizeDependencyPath)
}

function normalizeDependencyPath(path: string): string {
  const cleanedPath = path.replace(/\.+$/, '')
  const lastSlashIndex = cleanedPath.lastIndexOf('/')
  const lastDotIndex = cleanedPath.lastIndexOf('.')

  if (lastDotIndex <= lastSlashIndex) {
    return cleanedPath
  }

  const packageName = cleanedPath.slice(lastSlashIndex + 1, lastDotIndex)
  const objectName = cleanedPath.slice(lastDotIndex + 1)
  return packageName && packageName === objectName
    ? cleanedPath.slice(0, lastDotIndex)
    : cleanedPath
}

interface LegacyMaterialNodeBlock {
  className: string
  name: string
  body: string
}

interface LegacyMaterialPin {
  name: string
  friendlyName?: string
  defaultValue?: string
  autogeneratedDefaultValue?: string
  direction?: string
  hidden?: boolean
  defaultValueIgnored?: boolean
}

export interface ExtractedMaterialParameters {
  scalarParameters: MaterialParameterValue[]
  vectorParameters: MaterialParameterValue[]
  textureParameters: MaterialParameterValue[]
  staticSwitchParameters: MaterialParameterValue[]
}

function createEmptyExtractedParameters(): ExtractedMaterialParameters {
  return {
    scalarParameters: [],
    vectorParameters: [],
    textureParameters: [],
    staticSwitchParameters: []
  }
}

function normalizeLegacyClassName(className: string): string {
  const cleanClassName = className.replace(/^["']|["']$/g, '')
  return cleanClassName.split('.').pop() || cleanClassName.split('/').pop() || cleanClassName
}

function parseLegacyMaterialNodeBlocks(code: string): LegacyMaterialNodeBlock[] {
  const allBlocks: LegacyMaterialNodeBlock[] = []
  const stack: LegacyMaterialNodeBlock[] = []

  for (const line of code.split(/\r?\n/)) {
    const beginMatch = line.match(/^\s*Begin Object\b/)
    if (beginMatch) {
      if (stack.length) {
        stack[stack.length - 1].body += `${line}\n`
      }

      const classMatch = line.match(/\bClass="?([^"\s]+)"?/)
      const nameMatch = line.match(/\bName="([^"]+)"/)
      stack.push({
        className: classMatch?.[1] ? normalizeLegacyClassName(classMatch[1]) : '',
        name: nameMatch?.[1] || '',
        body: ''
      })
      continue
    }

    if (/^\s*End Object\b/.test(line)) {
      const block = stack.pop()
      if (block?.className && block.name) {
        allBlocks.push(block)
      }
      if (stack.length) {
        stack[stack.length - 1].body += `${line}\n`
      }
      continue
    }

    if (stack.length) {
      stack[stack.length - 1].body += `${line}\n`
    }
  }

  const expressionBlocks = allBlocks.filter((block) =>
    block.className.startsWith('MaterialExpression')
  )
  const expressionByName = new Map(expressionBlocks.map((block) => [block.name, block]))
  const wrappedExpressionNames = new Set<string>()
  const graphExpressionBlocks = allBlocks
    .filter((block) => block.className === 'MaterialGraphNode')
    .map((block) => {
      const expressionName = block.body.match(
        /MaterialExpression=[^\r\n]*(MaterialExpression[A-Za-z0-9_]+)/
      )?.[1]
      const expressionBlock = expressionName ? expressionByName.get(expressionName) : undefined
      if (!expressionBlock) return null
      wrappedExpressionNames.add(expressionBlock.name)
      return {
        className: expressionBlock.className,
        name: expressionBlock.name,
        body: `${expressionBlock.body}\n${block.body}`
      }
    })
    .filter((block): block is LegacyMaterialNodeBlock => Boolean(block))

  return [
    ...graphExpressionBlocks,
    ...expressionBlocks.filter((block) => !wrappedExpressionNames.has(block.name))
  ]
}

function getLegacyProperty(block: LegacyMaterialNodeBlock, key: string): string | undefined {
  const match = block.body.match(new RegExp(`^\\s*${key}=([^\\r\\n]+)`, 'm'))
  return match?.[1]?.trim()
}

function getLegacyPinProperty(pinText: string, key: string): string | undefined {
  const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const quotedMatch = pinText.match(new RegExp(`${escapedKey}="((?:\\\\.|[^"])*)"`))
  if (quotedMatch?.[1] !== undefined) {
    return quotedMatch[1].replace(/\\"/g, '"').trim()
  }

  const unquotedMatch = pinText.match(new RegExp(`${escapedKey}=([^,)]*)`))
  return unquotedMatch?.[1]?.trim()
}

function parseLegacyPinFriendlyName(value: string | undefined): string | undefined {
  if (!value) return undefined
  const quotedParts = [...value.matchAll(/"([^"]*)"/g)]
  const quotedText = quotedParts.at(-1)?.[1]
  return (quotedText || unquoteLegacyValue(value))?.trim()
}

function parseLegacyBooleanFlag(value: string | undefined): boolean | undefined {
  if (!value) return undefined
  if (/^true$/i.test(value)) return true
  if (/^false$/i.test(value)) return false
  return undefined
}

function parseLegacyMaterialPins(block: LegacyMaterialNodeBlock): LegacyMaterialPin[] {
  const pins: LegacyMaterialPin[] = []
  const pinPattern = /^\s*CustomProperties\s+Pin\s*\((.*)\)\s*$/gm

  for (const match of block.body.matchAll(pinPattern)) {
    const pinText = match[1] || ''
    pins.push({
      name: getLegacyPinProperty(pinText, 'PinName') || '',
      friendlyName: parseLegacyPinFriendlyName(getLegacyPinProperty(pinText, 'PinFriendlyName')),
      defaultValue: getLegacyPinProperty(pinText, 'DefaultValue'),
      autogeneratedDefaultValue: getLegacyPinProperty(pinText, 'AutogeneratedDefaultValue'),
      direction: getLegacyPinProperty(pinText, 'Direction'),
      hidden: parseLegacyBooleanFlag(getLegacyPinProperty(pinText, 'bHidden')),
      defaultValueIgnored: parseLegacyBooleanFlag(
        getLegacyPinProperty(pinText, 'bDefaultValueIsIgnored')
      )
    })
  }

  return pins
}

function unquoteLegacyValue(value: string | undefined): string | undefined {
  if (!value) return undefined
  return value.replace(/^["']|["']$/g, '').trim()
}

function parseLegacyNumber(value: string | undefined): number | undefined {
  const raw = unquoteLegacyValue(value)
  if (!raw) return undefined
  const parsed = Number.parseFloat(raw)
  return Number.isFinite(parsed) ? parsed : undefined
}

function parseLegacyBoolean(value: string | undefined): boolean | undefined {
  const raw = unquoteLegacyValue(value)
  if (!raw) return undefined
  if (/^(true|1)$/i.test(raw)) return true
  if (/^(false|0)$/i.test(raw)) return false
  return undefined
}

function parseLegacyVector(value: string | undefined): Record<string, number> | undefined {
  if (!value) return undefined
  const vector: Record<string, number> = {}

  for (const channel of ['R', 'G', 'B', 'A'] as const) {
    const match = value.match(new RegExp(`${channel}=(-?\\d+(?:\\.\\d+)?)`))
    if (match?.[1]) {
      vector[channel.toLowerCase()] = Number.parseFloat(match[1])
    }
  }

  return Object.keys(vector).length > 0 ? vector : undefined
}

function getLegacyNodeLabel(block: LegacyMaterialNodeBlock, field: string): string {
  const parameterName = unquoteLegacyValue(getLegacyProperty(block, 'ParameterName'))
  if (parameterName) return parameterName

  const description = unquoteLegacyValue(getLegacyProperty(block, 'Desc'))
  if (description) return `${description}.${field}`

  const compactClass = block.className.replace(/^MaterialExpression/, '')
  const compactName = block.name.replace(/^MaterialExpression/, '')
  return `${compactName || compactClass}.${field}`
}

function normalizeLegacyPinName(name: string | undefined): string {
  return (name || '').toLowerCase().replace(/[\s_-]/g, '')
}

function getLegacyPinValue(block: LegacyMaterialNodeBlock, aliases: string[]): string | undefined {
  const normalizedAliases = new Set(aliases.map(normalizeLegacyPinName))

  for (const pin of parseLegacyMaterialPins(block)) {
    if (pin.direction === 'EGPD_Output' || pin.hidden || pin.defaultValueIgnored) continue
    const normalizedPinNames = [
      normalizeLegacyPinName(pin.name),
      normalizeLegacyPinName(pin.friendlyName)
    ]
    if (!normalizedPinNames.some((name) => normalizedAliases.has(name))) continue

    const value = pin.defaultValue ?? pin.autogeneratedDefaultValue
    if (value !== undefined && value !== '') return value
  }

  return undefined
}

function createExtractedParameter(
  name: string,
  type: MaterialParameterValue['type'],
  value: unknown,
  source: MaterialParameterValue['source']
): MaterialParameterValue {
  return {
    name,
    type,
    overrideValue: value,
    isOverridden: false,
    source
  }
}

export function extractLegacyMaterialParameters(code: string): ExtractedMaterialParameters {
  const result = createEmptyExtractedParameters()
  if (!code.trim()) return result

  for (const block of parseLegacyMaterialNodeBlocks(code)) {
    const rawClass = block.className

    if (rawClass.includes('TextureSampleParameter')) {
      const textureValue = extractGamePaths(getLegacyProperty(block, 'Texture'))[0]
      result.textureParameters.push(
        createExtractedParameter(
          getLegacyNodeLabel(block, 'Texture'),
          'texture',
          textureValue || unquoteLegacyValue(getLegacyProperty(block, 'Texture')) || 'None',
          'parameter'
        )
      )
      continue
    }

    if (rawClass.includes('VectorParameter') || rawClass.includes('Constant3Vector')) {
      const vectorValue =
        parseLegacyVector(getLegacyProperty(block, 'DefaultValue')) ||
        parseLegacyVector(getLegacyProperty(block, 'Constant'))
      if (vectorValue) {
        result.vectorParameters.push(
          createExtractedParameter(
            getLegacyNodeLabel(block, 'Value'),
            'vector',
            vectorValue,
            rawClass.includes('VectorParameter') ? 'parameter' : 'nodeProperty'
          )
        )
      }
      continue
    }

    if (rawClass.includes('StaticSwitchParameter') || rawClass.includes('StaticBoolParameter')) {
      const boolValue =
        parseLegacyBoolean(getLegacyProperty(block, 'DefaultValue')) ??
        parseLegacyBoolean(getLegacyProperty(block, 'Value'))
      if (boolValue !== undefined) {
        result.staticSwitchParameters.push(
          createExtractedParameter(
            getLegacyNodeLabel(block, 'Value'),
            'staticSwitch',
            boolValue,
            'parameter'
          )
        )
      }
      continue
    }

    if (rawClass.includes('ScalarParameter') || rawClass === 'MaterialExpressionConstant') {
      const scalarValue =
        parseLegacyNumber(getLegacyPinValue(block, ['Value'])) ??
        parseLegacyNumber(getLegacyProperty(block, 'DefaultValue')) ??
        parseLegacyNumber(getLegacyProperty(block, 'R')) ??
        parseLegacyNumber(getLegacyProperty(block, 'Value'))
      if (scalarValue !== undefined) {
        result.scalarParameters.push(
          createExtractedParameter(
            getLegacyNodeLabel(block, 'Value'),
            'scalar',
            scalarValue,
            rawClass.includes('ScalarParameter') ? 'parameter' : 'nodeProperty'
          )
        )
      }
      continue
    }

    if (rawClass === 'MaterialExpressionTextureCoordinate') {
      const coordinateIndex =
        parseLegacyNumber(getLegacyPinValue(block, ['CoordinateIndex', 'Coordinate Index'])) ??
        parseLegacyNumber(getLegacyProperty(block, 'CoordinateIndex')) ??
        0
      result.scalarParameters.push(
        createExtractedParameter(
          getLegacyNodeLabel(block, 'Coordinate Index'),
          'scalar',
          coordinateIndex,
          'nodeProperty'
        )
      )

      for (const field of [
        { property: 'UTiling', label: 'U Tiling', aliases: ['UTiling', 'U Tiling'] },
        { property: 'VTiling', label: 'V Tiling', aliases: ['VTiling', 'V Tiling'] }
      ]) {
        const value =
          parseLegacyNumber(getLegacyPinValue(block, field.aliases)) ??
          parseLegacyNumber(getLegacyProperty(block, field.property))
        if (value !== undefined) {
          result.scalarParameters.push(
            createExtractedParameter(
              getLegacyNodeLabel(block, field.label),
              'scalar',
              value,
              'nodeProperty'
            )
          )
        }
      }

      for (const field of [
        { property: 'UnMirrorU', label: 'Un Mirror U', aliases: ['UnMirrorU', 'Un Mirror U'] },
        { property: 'UnMirrorV', label: 'Un Mirror V', aliases: ['UnMirrorV', 'Un Mirror V'] }
      ]) {
        const value =
          parseLegacyBoolean(getLegacyPinValue(block, field.aliases)) ??
          parseLegacyBoolean(getLegacyProperty(block, field.property))
        if (value !== undefined) {
          result.staticSwitchParameters.push(
            createExtractedParameter(
              getLegacyNodeLabel(block, field.label),
              'staticSwitch',
              value,
              'nodeProperty'
            )
          )
        }
      }
    }
  }

  return result
}

export function buildDependencyRecords(
  kind: MaterialDependency['kind'],
  paths: string[],
  assetLinks: Map<string, AssetLinkRecord> = new Map()
): MaterialDependency[] {
  return paths.map((path) => {
    const asset = assetLinks.get(path)
    return {
      path,
      name: asset?.assetName || path.split('/').pop() || path,
      kind,
      assetKey: asset?.assetKey,
      assetType: asset?.classNameCn || asset?.className,
      thumbnail: asset?.customPoster || asset?.imgLocalPath,
      isResolved: Boolean(asset?.assetKey)
    }
  })
}

export function summarizeLegacyGraph(code: string): MaterialGraphSummary {
  if (!code) return createEmptyGraphSummary()

  const nodeMatches = [
    ...code.matchAll(/Begin Object Class="?\/Script\/Engine\.(MaterialExpression[A-Za-z0-9_]+)"?/g)
  ].map((match) => match[1])
  const textureNodeCount = nodeMatches.filter(
    (name) => name === 'MaterialExpressionTextureSample'
  ).length
  const functionCallCount = nodeMatches.filter(
    (name) => name === 'MaterialExpressionMaterialFunctionCall'
  ).length
  const keyNodeClasses = [
    ...new Set(nodeMatches.map((name) => name.replace(/^MaterialExpression/, '')))
  ].slice(0, 5)

  return {
    nodeCount: nodeMatches.length,
    connectionCount: (code.match(/LinkedTo=\(/g) || []).length,
    keyNodeClasses,
    textureNodeCount,
    functionCallCount
  }
}

export function extractLegacyMaterialDependencies(code: string): {
  texturePaths: string[]
  functionPaths: string[]
  parameterCollectionPaths: string[]
} {
  const texturePaths = new Set<string>()
  const functionPaths = new Set<string>()
  const parameterCollectionPaths = new Set<string>()
  // 引号写成 {0,2}：UE5 导出的是 Texture2D'"/Game/..."'（单引号里套双引号），
  // 只允许一个引号的话，序列化器自己写出来的格式反而读不回来。
  const textureMatches =
    code.match(/Texture(?:Object)?=Texture(?:2D)?['"]{0,2}\/Game\/[A-Za-z0-9_./]+/g) || []
  const functionMatches =
    code.match(/MaterialFunction(?:=|Object=)[^/]*\/Game\/[A-Za-z0-9_./]+/g) || []
  const parameterCollectionMatches =
    code.match(/Collection(?:=|Object=)[^/]*\/Game\/[A-Za-z0-9_./]+/g) || []

  for (const match of textureMatches) {
    const pathMatch = match.match(/\/Game\/[A-Za-z0-9_./]+/g)
    if (pathMatch?.[0]) {
      texturePaths.add(normalizeDependencyPath(pathMatch[0]))
    }
  }

  for (const match of functionMatches) {
    const pathMatch = match.match(/\/Game\/[A-Za-z0-9_./]+/g)
    if (pathMatch?.[0]) {
      functionPaths.add(normalizeDependencyPath(pathMatch[0]))
    }
  }

  for (const match of parameterCollectionMatches) {
    const pathMatch = match.match(/\/Game\/[A-Za-z0-9_./]+/g)
    if (pathMatch?.[0]) {
      parameterCollectionPaths.add(normalizeDependencyPath(pathMatch[0]))
    }
  }

  return {
    texturePaths: [...texturePaths],
    functionPaths: [...functionPaths],
    parameterCollectionPaths: [...parameterCollectionPaths]
  }
}
