import { describe, expect, it } from 'vitest'
import { extractFunctionSignatureFromCode } from './blueprintCodeParser'

describe('extractFunctionSignatureFromCode', () => {
  it('extracts bool input and output pins from function entry and function result nodes', () => {
    const code = `Begin Object Class="/Script/BlueprintGraph.K2Node_FunctionEntry" Name="K2Node_FunctionEntry_0"
   CustomProperties Pin (PinId=EXECENTRY,PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,)
   CustomProperties Pin (PinId=SELFENTRY,PinName="self",PinType.PinCategory="object",PinType.PinSubCategory="self",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,)
   CustomProperties Pin (PinId=BOOLINPUT,PinName="NewParam",Direction="EGPD_Output",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,DefaultValue="false",AutogeneratedDefaultValue="false",)
End Object
Begin Object Class="/Script/BlueprintGraph.K2Node_FunctionResult" Name="K2Node_FunctionResult_0"
   CustomProperties Pin (PinId=EXECRESULT,PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,)
   CustomProperties Pin (PinId=BOOLOUTPUT,PinName="NewParam1",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,DefaultValue="false",AutogeneratedDefaultValue="false",)
End Object`

    const signature = extractFunctionSignatureFromCode(code)

    expect(signature.inputs).toEqual([
      {
        name: 'NewParam',
        type: 'Boolean',
        defaultValue: 'false'
      }
    ])
    expect(signature.outputs).toEqual([
      {
        name: 'NewParam1',
        type: 'Boolean',
        defaultValue: 'false'
      }
    ])
  })
})
